import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { Turkey } from '@/components/Turkey';
import { C } from '@/constants/colours';
import { SUPPORT_LINKS } from '@/constants/support';

const links=[
  {title:'Help & Support',copy:'Questions, troubleshooting and contact details.',icon:'help-buoy' as const,url:SUPPORT_LINKS.support},
  {title:'Privacy Policy',copy:'What stays on your device and how privacy works.',icon:'shield-checkmark' as const,url:SUPPORT_LINKS.privacy},
  {title:'Terms of Use',copy:'The straightforward rules for using the game.',icon:'document-text' as const,url:SUPPORT_LINKS.terms},
];

export default function Help(){return <Screen><View style={s.header}><Pressable accessibilityLabel="Back" onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={28} color={C.brown}/></Pressable><Text style={s.title}>HELP & LEGAL</Text><View style={s.headerSpacer}/></View><View style={s.hero}><View style={s.heroCopy}><Text style={s.eyebrow}>THE FARM OFFICE</Text><Text style={s.heroTitle}>NEED A HAND?</Text><Text style={s.heroText}>We’ll get your flock back on its feet.</Text></View><Turkey position="gobbler" size={112}/></View><Text style={s.section}>SUPPORT & INFORMATION</Text><View style={s.card}>{links.map((link,index)=><Pressable accessibilityRole="link" key={link.title} onPress={()=>Linking.openURL(link.url)} style={[s.row,index<links.length-1&&s.border]}><View style={s.icon}><Ionicons name={link.icon} size={23} color={C.red}/></View><View style={s.copy}><Text style={s.label}>{link.title}</Text><Text style={s.detail}>{link.copy}</Text></View><Ionicons name="open-outline" size={18} color={C.muted}/></Pressable>)}</View><View style={s.local}><Ionicons name="phone-portrait-outline" size={23} color={C.green}/><View style={s.copy}><Text style={s.localTitle}>YOUR GAME STAYS ON THIS DEVICE</Text><Text style={s.localText}>Toss the Turkeys has no account system, advertising or analytics. Game progress, player names, settings and statistics are stored locally.</Text></View></View><Text style={s.note}>These links open the Toss the Turkeys website in your browser.</Text></Screen>}

const s=StyleSheet.create({header:{height:48,flexDirection:'row',alignItems:'center'},back:{width:42,height:42,borderRadius:21,backgroundColor:'rgba(91,45,29,.08)',alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',fontFamily:'Baloo2_800ExtraBold',fontSize:25,lineHeight:31,paddingTop:2,color:C.ink},headerSpacer:{width:42},hero:{height:160,borderRadius:24,overflow:'hidden',backgroundColor:C.brown,flexDirection:'row',alignItems:'center',paddingLeft:20,marginTop:8},heroCopy:{flex:1,zIndex:2},eyebrow:{fontFamily:'Nunito_800ExtraBold',fontSize:9,letterSpacing:1.8,color:C.gold},heroTitle:{fontFamily:'Baloo2_800ExtraBold',fontSize:27,lineHeight:33,paddingTop:2,color:C.white},heroText:{fontFamily:'Nunito_700Bold',fontSize:11,lineHeight:16,color:C.parchment},section:{fontFamily:'Nunito_800ExtraBold',fontSize:10,letterSpacing:1.6,color:C.muted,marginTop:20,marginBottom:7},card:{borderRadius:20,borderWidth:1.5,borderColor:C.line,backgroundColor:C.white,paddingHorizontal:14},row:{minHeight:78,flexDirection:'row',alignItems:'center',gap:12},border:{borderBottomWidth:1,borderBottomColor:C.line},icon:{width:43,height:43,borderRadius:14,backgroundColor:'#FCE8DD',alignItems:'center',justifyContent:'center'},copy:{flex:1},label:{fontFamily:'Baloo2_800ExtraBold',fontSize:17,lineHeight:21,paddingTop:1,color:C.ink},detail:{fontFamily:'Nunito_400Regular',fontSize:10,lineHeight:14,color:C.muted},local:{marginTop:14,padding:15,borderRadius:18,backgroundColor:'#EEF5E7',borderWidth:1.5,borderColor:'#D4E4C7',flexDirection:'row',alignItems:'flex-start',gap:12},localTitle:{fontFamily:'Nunito_800ExtraBold',fontSize:9,letterSpacing:.7,color:C.green},localText:{fontFamily:'Nunito_700Bold',fontSize:10,lineHeight:15,color:C.muted,marginTop:3},note:{fontFamily:'Nunito_700Bold',fontSize:9,color:C.muted,textAlign:'center',marginTop:16}});
