import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { ScreenTitle } from '@/components/ScreenTitle';
import { C } from '@/constants/colours';
import { useSettingsStore } from '@/store/settingsStore';
import { useStatisticsStore } from '@/store/statisticsStore';

export default function Settings() {
  const settings = useSettingsStore(); const stats = useStatisticsStore();
  return <Screen><ScreenTitle title="SETTINGS" subtitle="Tune the table to your liking." /><View style={s.card}><Toggle label="SOUND EFFECTS" value={settings.sound} onPress={() => settings.toggle('sound')} /><Toggle label="HAPTICS" value={settings.haptics} onPress={() => settings.toggle('haptics')} /><Toggle label="ANIMATIONS" value={settings.animations} onPress={() => settings.toggle('animations')} last /></View><Text style={s.section}>LIFETIME STATS</Text><View style={s.stats}><Stat label="GAMES" value={stats.gamesPlayed} /><Stat label="TOSSES" value={stats.totalTosses} /><Stat label="POINTS" value={stats.totalPointsScored} /><Stat label="PLUCKED" value={stats.pluckedCount} /><Stat label="BEST TURN" value={stats.highestTurnScore} /><Stat label="BEST TOSS" value={stats.highestSingleTossScore} /></View><Text style={s.foot}>Settings, recent names, and lifetime statistics are stored only on this device.</Text></Screen>;
}
function Toggle({ label, value, onPress, last = false }: { label: string; value: boolean; onPress: () => void; last?: boolean }) { return <Pressable onPress={onPress} style={[s.row, !last && s.border]}><Text style={s.label}>{label}</Text><View style={[s.toggle, value && s.toggleOn]}><View style={[s.knob, value && s.knobOn]} /></View></Pressable>; }
function Stat({ label, value }: { label: string; value: number }) { return <View style={s.stat}><Text style={s.value}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>; }
const s = StyleSheet.create({ card: { backgroundColor: C.white, borderRadius: 20, borderWidth: 1.5, borderColor: C.line, paddingHorizontal: 16 }, row: { height: 67, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, border: { borderBottomWidth: 1, borderBottomColor: C.line }, label: { fontFamily: 'Nunito_800ExtraBold', fontSize: 14, color: C.ink, letterSpacing: .6 }, toggle: { width: 54, height: 31, borderRadius: 16, backgroundColor: '#D5C9BD', padding: 3 }, toggleOn: { backgroundColor: C.green }, knob: { width: 25, height: 25, borderRadius: 13, backgroundColor: C.white }, knobOn: { alignSelf: 'flex-end' }, section: { fontFamily: 'Nunito_800ExtraBold', fontSize: 12, letterSpacing: 1.5, color: C.muted, marginTop: 28, marginBottom: 10 }, stats: { flexDirection: 'row', flexWrap: 'wrap', backgroundColor: C.brown, borderRadius: 20, paddingVertical: 12 }, stat: { width: '33.33%', alignItems: 'center', padding: 12 }, value: { fontFamily: 'Baloo2_800ExtraBold', fontSize: 27, lineHeight: 35, paddingTop: 2, color: C.gold }, statLabel: { fontFamily: 'Nunito_800ExtraBold', fontSize: 9, color: C.parchment, letterSpacing: .6 }, foot: { fontFamily: 'Nunito_400Regular', fontSize: 12, lineHeight: 18, color: C.muted, textAlign: 'center', margin: 22 } });
