import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { Turkey } from '@/components/Turkey';
import { C } from '@/constants/colours';
import { useSettingsStore } from '@/store/settingsStore';
import { useStatisticsStore } from '@/store/statisticsStore';

const landingNames={pronePoultryCount:'Prone Poultry',beakyOneCount:'Beaky One',gobblerCount:'Gobbler',turkeyTrotCount:'Turkey Trot',jibletsCount:'Jiblets',wattleWobbleCount:'Wattle Wobble'} as const;

export default function Settings(){
  const settings=useSettingsStore(),stats=useStatisticsStore();
  const favourite=(Object.keys(landingNames) as (keyof typeof landingNames)[]).reduce((best,key)=>stats[key]>stats[best]?key:best,'gobblerCount');
  const pluckRate=stats.totalTosses?Math.round(stats.pluckedCount/stats.totalTosses*100):0;
  return <Screen>
    <View style={s.heading}><Text style={s.pageTitle}>SETTINGS</Text><Text style={s.subtitle}>Make the coop feel just right.</Text></View>
    <View style={s.hero}><View style={s.heroCopy}><Text style={s.heroEyebrow}>YOUR COOP</Text><Text style={s.heroTitle}>PLAY IT YOUR WAY</Text><Text style={s.heroText}>Every switch is saved on this device.</Text></View><Turkey position="turkey_trot" size={82}/></View>
    <Text style={s.section}>GAME FEEL</Text>
    <View style={s.card}><Toggle icon="musical-notes" label="Background music" detail="A gentle looping country tune" value={settings.music} onPress={()=>settings.toggle('music')}/><Toggle icon="volume-high" label="Turkey sounds" detail="Gobbles, landings and celebrations" value={settings.sound} onPress={()=>settings.toggle('sound')}/><Toggle icon="phone-portrait" label="Haptic bumps" detail="Feel impacts and risky results" value={settings.haptics} onPress={()=>settings.toggle('haptics')}/><Toggle icon="sparkles" label="Full animation" detail="Physics, feathers and flapping" value={settings.animations} onPress={()=>settings.toggle('animations')}/><Toggle icon="partly-sunny" label="Farm conditions" detail="A new condition every full player round" value={settings.farmConditions} onPress={()=>settings.toggle('farmConditions')} last/></View>
    <Text style={s.section}>LUCK REPORT</Text>
    <View style={s.report}><View><Text style={s.reportLabel}>FAVOURITE LANDING</Text><Text style={s.reportValue}>{stats.totalTosses?landingNames[favourite]:'No tosses yet'}</Text></View><View style={s.rate}><Text style={s.rateValue}>{pluckRate}%</Text><Text style={s.rateLabel}>PLUCK RATE</Text></View></View>
    <View style={s.stats}><Stat icon="game-controller" label="GAMES" value={stats.gamesPlayed}/><Stat icon="repeat" label="TOSSES" value={stats.totalTosses}/><Stat icon="star" label="POINTS" value={stats.totalPointsScored}/><Stat icon="alert-circle" label="PLUCKED" value={stats.pluckedCount}/><Stat icon="trending-up" label="BEST TURN" value={stats.highestTurnScore}/><Stat icon="trophy" label="BEST TOSS" value={stats.highestSingleTossScore}/></View>
    <Pressable onPress={()=>router.push('/trophy-coop')} style={{minHeight:54,borderRadius:16,backgroundColor:'#FFF1D7',borderWidth:1.5,borderColor:C.line,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:10,marginBottom:5}}><View style={{width:36,height:36,borderRadius:18,backgroundColor:C.gold,alignItems:'center',justifyContent:'center'}}><Ionicons name="trophy" size={19} color={C.brown}/></View><View style={{flex:1}}><Text style={{fontFamily:'Baloo2_800ExtraBold',fontSize:14,lineHeight:18,paddingTop:2,color:C.brown}}>TROPHY COOP</Text><Text style={{fontFamily:'Nunito_700Bold',fontSize:8,color:C.muted}}>Achievements, rare finds and barnyard glory</Text></View><Ionicons name="chevron-forward" size={19} color={C.muted}/></Pressable>
  </Screen>;
}

function Toggle({icon,label,detail,value,onPress,last=false}:{icon:keyof typeof Ionicons.glyphMap;label:string;detail:string;value:boolean;onPress:()=>void;last?:boolean}){return <Pressable accessibilityRole="switch" accessibilityState={{checked:value}} onPress={onPress} style={[s.row,{minHeight:48},!last&&s.border]}><View style={[s.iconBadge,value&&s.iconBadgeOn]}><Ionicons name={icon} size={19} color={value?C.red:C.muted}/></View><View style={s.rowCopy}><Text style={s.label}>{label}</Text><Text style={s.detail}>{detail}</Text></View><View style={[s.toggle,value&&s.toggleOn]}><View style={[s.knob,value&&s.knobOn]}/></View></Pressable>}
function Stat({icon,label,value}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:number}){return <View style={s.stat}><Ionicons name={icon} size={15} color={C.tan}/><Text style={s.value}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}

const s=StyleSheet.create({heading:{alignItems:'center',marginBottom:9},pageTitle:{fontFamily:'Baloo2_800ExtraBold',fontSize:27,lineHeight:34,paddingTop:2,color:C.ink},subtitle:{fontFamily:'Nunito_400Regular',fontSize:12,lineHeight:16,color:C.muted},hero:{height:88,borderRadius:18,backgroundColor:C.brown,overflow:'hidden',paddingLeft:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},heroCopy:{flex:1,zIndex:2},heroEyebrow:{fontFamily:'Nunito_800ExtraBold',fontSize:8,letterSpacing:1.5,color:C.gold},heroTitle:{fontFamily:'Baloo2_800ExtraBold',fontSize:18,lineHeight:23,color:C.white,paddingTop:1},heroText:{fontFamily:'Nunito_700Bold',fontSize:8.5,color:C.parchment},section:{fontFamily:'Nunito_800ExtraBold',fontSize:9.5,letterSpacing:1.4,color:C.muted,marginTop:11,marginBottom:5},card:{backgroundColor:C.white,borderRadius:17,borderWidth:1.5,borderColor:C.line,paddingHorizontal:12},row:{minHeight:54,flexDirection:'row',alignItems:'center',gap:9},border:{borderBottomWidth:1,borderBottomColor:C.line},iconBadge:{width:32,height:32,borderRadius:10,backgroundColor:'#EFE9E1',alignItems:'center',justifyContent:'center'},iconBadgeOn:{backgroundColor:'#FCE8DD'},rowCopy:{flex:1},label:{fontFamily:'Nunito_800ExtraBold',fontSize:11.5,color:C.ink},detail:{fontFamily:'Nunito_400Regular',fontSize:8.5,lineHeight:11,color:C.muted},toggle:{width:43,height:25,borderRadius:13,backgroundColor:'#D5C9BD',padding:3},toggleOn:{backgroundColor:C.green},knob:{width:19,height:19,borderRadius:10,backgroundColor:C.white},knobOn:{alignSelf:'flex-end'},report:{minHeight:56,borderRadius:15,backgroundColor:'#FFF1D7',borderWidth:1.5,borderColor:C.line,paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},reportLabel:{fontFamily:'Nunito_800ExtraBold',fontSize:7,letterSpacing:1,color:C.muted},reportValue:{fontFamily:'Baloo2_800ExtraBold',fontSize:15,color:C.brown},rate:{alignItems:'center',paddingLeft:13,borderLeftWidth:1,borderLeftColor:C.line},rateValue:{fontFamily:'Baloo2_800ExtraBold',fontSize:20,lineHeight:23,color:C.red},rateLabel:{fontFamily:'Nunito_800ExtraBold',fontSize:6.5,color:C.muted,letterSpacing:.6},stats:{flexDirection:'row',flexWrap:'wrap',backgroundColor:C.brown,borderRadius:17,paddingVertical:3,marginTop:6,marginBottom:5},stat:{width:'33.33%',alignItems:'center',paddingVertical:5},value:{fontFamily:'Baloo2_800ExtraBold',fontSize:18,lineHeight:21,paddingTop:0,color:C.gold},statLabel:{fontFamily:'Nunito_800ExtraBold',fontSize:6.5,color:C.parchment,letterSpacing:.4}});
